### ISSUE TITLE
"Successfully reverted to backup"

### ISSUE THREAD

**Issue by smdlion** [connordennison/phasmoeditor#14]
Hey, just wondering if you could teach us how to edit save file correctly

**Comment by cnnrde** [comment]
Yep - I'll look into the issue (as others have had the same error) and will make a video explaining how to use the editor.

**Comment by smdlion** [comment]
Appreciate it man and I feel embarrassed cuz I found button "download save file" after I sent you an issue, I was like "Why is there only an encrypted version of a file? How do I incrypt it?" And then at night, when I was trying to sleep, I remembered blue button named "Download save file" which I couldn't find :D
But the video could help other people to understand properly what to do.

**Comment by cnnrde** [comment]
No worries - thanks for checking out my project!

**Comment by smdlion** [comment]
Project works fine, thank you brother
