### ISSUE TITLE
After updating phasmophobia phasmoeditor.cnnd.dev stopped working (

### ISSUE THREAD

**Issue by Konanets** [connordennison/phasmoeditor#4]
fix pls

**Comment by alextusinean** [comment]
If you're still having issues you can use https://es3.lol as an alternative 😃

**Comment by cnnrde** [comment]
I've not been able to recreate this. Please try deleting your save file, launching the game, closing the game, and then re-uploading your safe file.

**Comment by InzGIBA** [comment]
Try the instructions in the "Important Notice" section

**Comment by herokillerJ** [comment]
> 请尝试“重要通知”部分中的说明

not work
