### ISSUE TITLE
The editor is not available

### ISSUE THREAD

**Issue by hk75233** [connordennison/phasmoeditor#5]
While I was improving my reputation, The editor is not available. Please repair as soon as possible, thanks ~~~

**Comment by alextusinean** [comment]
If you're still having issues you can use https://es3.lol as an alternative 😃

**Comment by cnnrde** [comment]
Hey, could you elaborate? Screenshots / screen recordings would be handy

**Comment by nullptr-v** [comment]
kinetic games has released a patch yesterday to patch the savefile editor https://store.steampowered.com/news/app/739630/view/3655287211045440641
![image](https://github.com/connordennison/phasmoeditor/assets/100923803/d8f4e1dd-9ddd-4357-948c-eb2311f3c97c)

**Comment by InzGIBA** [comment]
Try the instructions in the "Important Notice" section

**Comment by cnnrde** [comment]
Editor isn't patched, just confirmed that it still works as of the latest update
