### ISSUE TITLE
Will this get me banned?

### ISSUE THREAD

**Issue by thaatds233** [connordennison/phasmoeditor#6]
I know this isn't an issue with the program itself but, I've seen people getting banned for editing their save file. I just want to give myself infinite money but I don't want to get a game ban on my account.

**Comment by cnnrde** [comment]
There is a possibility you can get banned. From personal experience, I've had no issues. I'd recommend that you don't give yourself too much money and don't set your level ridiculously high. I can't guarantee that you'll be 100% safe when following these, but as long as you don't ruin the experience for other players you should be fine.

**Comment by piemadd** [comment]
Yes
