### ISSUE TITLE
Safety

### ISSUE THREAD

**Issue by Omy-meow** [connordennison/phasmoeditor#7]
Hiya, not so much an issue but wondering how safe it is to use it since the update? Are there anythings in particular we should be careful to change etc to avoid getting detected. Thanks

**Comment by cnnrde** [comment]
I can't guarantee any level of safety with this save editor. From my testing, I have not run into any issues with detection and the likes but it should generally boil down to 3 rules:
1. Don't give yourself a ridiculous amount of levels to show off
2. Don't ruin the game for others
3. Only give yourself the bare minimum (in terms of money) to buy what you desire.
I've also not tested this in public lobbies (only private and singleplayer). There's a chance that if someone catches you - and reports you - you will end up banned
