### ISSUE TITLE
Save File error

### ISSUE THREAD

**Issue by Ravbid** [connordennison/phasmoeditor#8]
when i try to upload my save file it keep saying that "Error decrypting save file - make sure you're using the correct file (and that it's valid)" but when i use it earlier it was fine only change my prestige

**Comment by InzGIBA** [comment]
Try the instructions in the "Important Notice" section

**Comment by rmurdo1997** [comment]
Im getting the error as well, was working fine a minute ago

**Comment by InzGIBA** [comment]
> Im getting the error as well, was working fine a minute ago

- Try disabling the Steam Cloud synchronization feature
- Play one game in any mode
- Quit the game and restart your computer
- Use the tool (phasmoeditor) to check the saved file

**Comment by cnnrde** [comment]
Seems to be an issue with save files corrupting somewhat (from my tests), the solution provided by @InzGIBA should work but the alternative option is to just delete your save file, follow those steps (turning Steam Cloud off, etc) and then re-upload the file to the editor and make your edits again.
